# ============================================================
# HYDE — Hypothetical Document Embeddings for Enhanced Retrieval
# ============================================================
#
# ╔══════════════════════════════════════════════════════════╗
# ║  HYDE IS A RESEARCH TECHNIQUE THAT DRAMATICALLY         ║
# ║  IMPROVES RAG RETRIEVAL BY BRIDGING THE                 ║
# ║  "QUERY-DOCUMENT SEMANTIC GAP"                          ║
# ╚══════════════════════════════════════════════════════════╝
#
# ─────────────────────────────────────────────────────────
# THE PROBLEM HYDE SOLVES: SEMANTIC MISMATCH
# ─────────────────────────────────────────────────────────
#
#   In standard RAG, we embed the USER'S QUESTION and search
#   for similar document chunks. But there's a fundamental
#   problem: questions and answers are semantically DIFFERENT.
#
#   EXAMPLE:
#     Question: "Was a weapon found at the scene?"
#     Relevant chunk: "A kitchen knife with blood traces was
#                     recovered from the living room floor."
#
#   The question talks about "weapon" + "found" + "scene"
#   The answer talks about "knife" + "blood traces" + "living room"
#
#   Even though they're about the SAME topic, their embeddings
#   may not be very close because:
#     - Different vocabulary (weapon ≠ knife)
#     - Different structure (question ≠ statement)
#     - Different focus (asking vs. describing)
#
#   RESULT: The correct chunk might rank #4 or #5 instead of #1.
#   With only Top-K=5, we might MISS critical evidence entirely.
#
# ─────────────────────────────────────────────────────────
# HOW HYDE FIXES THIS
# ─────────────────────────────────────────────────────────
#
#   Instead of embedding the question directly, HYDE:
#
#   Step 1: Generate a HYPOTHETICAL answer to the question
#           using the LLM (WITHOUT any context — pure hallucination)
#
#   Step 2: Embed the HYPOTHETICAL answer (not the question!)
#
#   Step 3: Search FAISS using that embedding
#
#   WHY THIS WORKS:
#   The hypothetical answer is WRITTEN LIKE A DOCUMENT, not like a question.
#   It will naturally contain similar vocabulary and structure to the
#   actual document chunks stored in FAISS.
#
#   EXAMPLE:
#     Question: "Was a weapon found at the scene?"
#     
#     Hypothetical answer (generated by LLM):
#       "Based on the forensic examination, a sharp-edged weapon
#        consistent with a kitchen knife was recovered from the
#        crime scene. The weapon showed traces of biological
#        material on the blade surface."
#     
#     Actual stored chunk:
#       "A kitchen knife with blood traces was recovered from
#        the living room floor."
#
#   The hypothetical answer and the stored chunk now share:
#     "kitchen knife", "recovered", "traces", "weapon"
#   → Their embeddings are MUCH closer!
#   → The correct chunk now ranks #1 instead of #4!
#
# ─────────────────────────────────────────────────────────
# HYDE IMPROVES RECALL — HERE'S WHY
# ─────────────────────────────────────────────────────────
#
#   RECALL = (relevant chunks retrieved) / (total relevant chunks)
#
#   Without HYDE (Top-5):
#     Retrieved: [chunk_7, chunk_2, chunk_15, chunk_4*, chunk_9*]
#     Relevant:  [chunk_4*, chunk_9*, chunk_22]
#     Recall = 2/3 = 66.7%  (missed chunk_22!)
#
#   With HYDE (Top-5):
#     Retrieved: [chunk_4*, chunk_9*, chunk_22*, chunk_7, chunk_15]
#     Relevant:  [chunk_4*, chunk_9*, chunk_22*]
#     Recall = 3/3 = 100%  (all relevant chunks found!)
#
#   HYDE shifted the query embedding into "document space"
#   which made ALL relevant chunks detectable.
#
# ─────────────────────────────────────────────────────────
# HOW HYDE REDUCES SEMANTIC MISMATCH (MATHEMATICAL VIEW)
# ─────────────────────────────────────────────────────────
#
#   In vector space:
#     Question embedding Q lives in "QUESTION SPACE"
#     Document embeddings D₁, D₂, ... live in "DOCUMENT SPACE"
#
#   These two spaces are DIFFERENT regions of the 384D embedding space.
#
#   Standard retrieval: Search from Q → must bridge the gap to D
#     distance(Q, D_relevant) = LARGE (different text styles)
#
#   HYDE retrieval: Generate hypothetical H, then search from H
#     distance(H, D_relevant) = SMALL (same text style!)
#
#   Conceptually:
#     Question Space ─────gap─────→ Document Space
#          Q                            D₁, D₂, D₃
#
#     With HYDE:
#     Question → LLM → Hypothetical H → embed → H₁
#                                                 ↓
#     Now H₁ is IN Document Space: H₁ ≈ D₁
#                                           → distance is tiny!
#
# ─────────────────────────────────────────────────────────
# TRADEOFFS AND CONSIDERATIONS
# ─────────────────────────────────────────────────────────
#
#   PROS:
#     + Dramatically better recall (10-30% improvement typical)
#     + Works with ANY embedding model (no retraining needed)
#     + Zero changes to the indexing pipeline
#     + Easy to toggle on/off via config flag
#
#   CONS:
#     - Extra LLM API call per query (adds ~0.5-1s latency)
#     - Extra API cost (one Groq inference per question)
#     - Hypothetical answer may introduce BIAS if LLM hallucinates
#       in the wrong direction (e.g., guesses "gun" when answer is "knife")
#     - Temperature must be LOW (0.2) to minimize hallucination variance
#
#   MITIGATION:
#     We use temperature=0.2 for hypothetical generation.
#     This keeps the hypothetical answer conservative and factual.
#     Even if it hallucinates details, the STRUCTURE and VOCABULARY
#     of a forensic report are still captured, which is what matters
#     for embedding similarity.
#
# ─────────────────────────────────────────────────────────
# RESEARCH REFERENCE
# ─────────────────────────────────────────────────────────
#   Paper: "Precise Zero-Shot Dense Retrieval without Relevance Labels"
#   Authors: Luyu Gao, Xueguang Ma, Jimmy Lin, Jamie Callan
#   Published: ACL 2023 (Carnegie Mellon University)
#   Key finding: HYDE outperforms standard dense retrieval by
#                ~10-20% on multiple benchmarks without any
#                training data or fine-tuning.
# ============================================================

from groq import Groq
from config import GROQ_API_KEY, GROQ_MODEL
import time

# Initialize Groq client for hypothetical document generation
_hyde_client = Groq(api_key=GROQ_API_KEY)


# ============================================================
# HYDE GENERATION PROMPT
# ============================================================
# This prompt instructs the LLM to generate a HYPOTHETICAL
# forensic document that ANSWERS the user's question.
#
# KEY DESIGN DECISIONS:
#   1. "Write a detailed forensic report paragraph" — ensures
#      document-style output (not conversational)
#   2. "Do NOT ask clarifying questions" — prevents the LLM
#      from generating a question back (would defeat HYDE)
#   3. "Include specific forensic terminology" — maximizes
#      vocabulary overlap with actual forensic documents
#   4. "Keep to 2-3 sentences" — we don't need a novel,
#      just enough text style to shift the embedding
#   5. Temperature 0.2 — low variance, conservative guesses
# ============================================================

HYDE_SYSTEM_PROMPT = """You are a forensic report writing assistant. 
When given a question about a crime scene or forensic evidence, write a SHORT 
hypothetical forensic document paragraph (2-4 sentences) that would ANSWER 
that question.

RULES:
- Write as if you are writing a section of an actual forensic incident report
- Use specific forensic terminology and professional language
- Include plausible specific details (types of evidence, locations, conditions)
- Do NOT say "hypothetically" or "this is an example" — write as if it's real
- Do NOT ask questions — only write declarative forensic statements
- Keep it focused and concise (2-4 sentences maximum)
- Write in third person, past tense (forensic report style)

PURPOSE: Your output will be embedded for semantic search, so use vocabulary 
that would appear in actual forensic documents."""


def generate_hypothetical_document(question: str) -> str:
    """
    Generate a hypothetical forensic document that answers the user's question.

    This is the core of HYDE (Hypothetical Document Embeddings).
    The LLM generates a plausible answer WITHOUT any real context.
    This "hallucinated" answer is then embedded and used as the
    query vector for FAISS search.

    Args:
        question: The user's original question.

    Returns:
        A short hypothetical forensic document paragraph (2-4 sentences).

    EXAMPLE:
    ─────────
    Input:  "Was a weapon found at the scene?"
    
    Output: "During the scene examination, investigators recovered a 
             kitchen knife (serrated blade, approximately 22cm) from 
             the living room floor, approximately 1.5 meters from the 
             victim's position. The blade exhibited dark reddish-brown 
             discoloration consistent with dried hematic residue, and 
             latent prints were lifted from the handle for AFIS comparison."
    
    This output will be EMBEDDED and used for FAISS search.
    It will match better against stored forensic chunks than the
    original question "Was a weapon found at the scene?"

    WHY LOW TEMPERATURE (0.2)?
    ───────────────────────────
    We want the hypothetical answer to be CONSERVATIVE — close to
    what a typical forensic document would say. High temperature
    would introduce wild/creative guesses that could push the
    embedding in the wrong direction, causing retrieval of
    irrelevant chunks.
    
    Think of it like fishing:
    - High temp = casting a very wide net → catches relevant AND junk
    - Low temp = casting a precise net → catches mostly relevant fish
    """
    print(f"\n[HYDE] Generating hypothetical document for: '{question}'")

    try:
        # Generate hypothetical forensic document
        # We use the same Groq API but with a different prompt and lower temperature
        last_err = None
        for attempt in range(3):
            try:
                response = _hyde_client.chat.completions.create(
                    messages=[
                        {"role": "system", "content": HYDE_SYSTEM_PROMPT},
                        {"role": "user", "content": f"Write a forensic report paragraph answering: {question}"}
                    ],
                    model=GROQ_MODEL,
                    temperature=0.2,     # Very low — conservative, factual guesses
                    max_tokens=256,      # Short output — just need vocabulary and structure
                )
                break
            except Exception as conn_err:
                last_err = conn_err
                print(f"[HYDE] Attempt {attempt + 1}/3 failed: {conn_err}")
                if attempt < 2:
                    time.sleep(1)
        else:
            raise last_err  # type: ignore

        hypothetical_doc = response.choices[0].message.content.strip()

        print(f"[HYDE] Generated hypothetical document ({len(hypothetical_doc)} chars):")
        print(f"  '{hypothetical_doc[:150]}...'")

        return hypothetical_doc

    except Exception as e:
        # FALLBACK: If HYDE generation fails, fall back to original question
        # This ensures the system still works even if the LLM call fails.
        # The retrieval just won't have the HYDE improvement.
        print(f"[HYDE] ⚠️  Generation failed: {e}")
        print(f"[HYDE] Falling back to original question for embedding")
        return question
